# Generated by Django 5.0.6 on 2024-07-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('admin_id', models.CharField(max_length=20, unique=True)),
                ('admin_password', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Admin',
                'db_table': 'Admin',
            },
        ),
    ]
