# Generated by Django 5.0.6 on 2024-07-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addproductmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_product_id', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'AProduct',
                'db_table': 'AProduct',
            },
        ),
    ]
