# Generated by Django 5.0.6 on 2024-07-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=20)),
                ('product_price', models.IntegerField()),
                ('product_status', models.CharField(default='Instock', max_length=50)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_colour', models.CharField(max_length=20)),
                ('product_brand', models.CharField(max_length=30)),
                ('product_wieght', models.CharField(max_length=20)),
                ('product_description', models.CharField(max_length=500)),
            ],
        ),
    ]
