# Generated by Django 5.0.6 on 2024-07-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_wieght',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='product_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_brand',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_colour',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_status',
            field=models.CharField(default='Instock', max_length=50, null=True),
        ),
    ]
