# Generated by Django 5.0.6 on 2024-07-05 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_cart_id', models.CharField(max_length=20, unique=True)),
                ('cart_quantity', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_user.customermodel')),
            ],
            options={
                'verbose_name_plural': 'Cart',
                'db_table': 'Cart',
            },
        ),
    ]
