# Generated by Django 5.0.6 on 2024-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_cart_id', models.CharField(max_length=20, unique=True)),
                ('cart_quantity', models.IntegerField()),
            ],
        ),
    ]
