# Generated by Django 5.0.6 on 2024-07-05 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=20, unique=True)),
                ('payment_date', models.DateTimeField()),
                ('payment_amount', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer_user.customermodel')),
            ],
        ),
    ]
