# Generated by Django 5.0.6 on 2024-07-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermodel',
            options={'verbose_name_plural': 'Customer'},
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='customer_first_name',
        ),
        migrations.RemoveField(
            model_name='customermodel',
            name='customer_last_name',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='customer_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='customermodel',
            table='Customer',
        ),
    ]
